[package]
name = "fft_utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utils = { path = "../utils" }
ark-ff = "0.5.0"
ark-std = "0.4.0"
